### 2. Matrices

#### How a matrix is formed

These elements are obtained from the system of linear equations:

$$\
a_1x + b_1y + c_1z = d_1\\
a_2x + b_2y + c_2z = d_2\\
a_3x + b_3y + c_3z = d_3\\
$$

$$\begin{bmatrix}
a_1 & b_1 & c_1\\
a_2 & b_2 & c_2\\
a_3 & b_3 & c_3
\end{bmatrix}
\begin{bmatrix}
x\\
y\\
z
\end{bmatrix}
=
\begin{bmatrix}
d_1\\
d_2\\
d_3
\end{bmatrix}$$
   

#### Basic Matrix Operations

In [3]:
import numpy as np

##### Matrix addition

In [4]:
A = np.array([
    [2, 3],
    [4, 5],
])

B = np.array([
    [6, 7],
    [8, 9],
])

A + B

array([[ 8, 10],
       [12, 14]])

##### Matrix Substraction

In [5]:
A = np.array([
    [2, 3],
    [4, 5],
])

B = np.array([
    [6, 7],
    [8, 9],
])

A - B

array([[-4, -4],
       [-4, -4]])

##### Dimensions of a Matrix

In [6]:
A.shape

(2, 2)

##### Creating a matrix with random values

In [7]:
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(20, size=(3, 3))
print(mat1, mat2, sep='\n')

[[5 2 6]
 [5 4 7]
 [3 7 1]]
[[10  3 18]
 [17 13 10]
 [ 6  5 15]]


In [8]:
print(np.add(mat1, mat2))
print(np.subtract(mat1, mat2))

[[15  5 24]
 [22 17 17]
 [ 9 12 16]]
[[ -5  -1 -12]
 [-12  -9  -3]
 [ -3   2 -14]]


##### Matrix Multiplication

In [9]:
# Multiplying a matrix by a scaler
x = 5
X = np.random.randint(5, size=(3, 3))

print(X)
print(x * X)
print(np.multiply(x, X))

[[0 0 4]
 [0 4 0]
 [1 2 2]]
[[ 0  0 20]
 [ 0 20  0]
 [ 5 10 10]]
[[ 0  0 20]
 [ 0 20  0]
 [ 5 10 10]]


In [10]:
# Multiplying two matrices element wise:
X = np.random.randint(10, size=(3,3))
I = np.eye(3, 3)
print(X)
print(np.multiply(X, I))

[[7 6 9]
 [3 3 1]
 [4 1 5]]
[[7. 0. 0.]
 [0. 3. 0.]
 [0. 0. 5.]]


In [11]:
# Matrix multiplication
print(np.matmul(X, I))

[[7. 6. 9.]
 [3. 3. 1.]
 [4. 1. 5.]]


## Extras
1. Trace
2. Transpose
3. Properties 
4. Types of Matrices
5. Symmetric and Skew-Symmetric Matrices
6. Adjoint
7. Inverse