## 7. Singular Value Decomposition

### Singular Value Decomposition (SVD)

Singular Value Decomposition (SVD) is a fundamental concept in linear algebra, where a matrix \( A \) is decomposed into three matrices as follows:

$$[ A = U \Sigma V^T ]$$

where:
- $U$ is an $m \times m$ unitary matrix (i.e., $U^T U = I$, where $I$ is the identity matrix).
- $\Sigma$ is an $m \times n$ rectangular diagonal matrix containing the singular values of $A$.
- $V^T$ is an $n \times n$ unitary matrix.

SVD is a powerful technique used in various applications such as dimensionality reduction, data compression, and least squares regression.



In [1]:
#### Python Implementation

#You can use libraries like NumPy to compute the Singular Value Decomposition of a matrix. Here's an example Python code:


import numpy as np

# Define a matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute Singular Value Decomposition
U, Sigma, Vt = np.linalg.svd(A)

# Print results
print("U matrix:")
print(U)
print("\nSigma matrix:")
print(np.diag(Sigma))
print("\nV transpose matrix:")
print(Vt)


U matrix:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

Sigma matrix:
[[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33475287e-16]]

V transpose matrix:
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
